# Add base classes missing from the XML input file
MISSING_BASE_CLASSES = {}

# Doc strings to replace some of the confusing ones generated by swig
# Indexed by (className, methodName)
DOC_STRINGS = {}

# Do not generate wrappers for the following methods.
# Indexed by (className, [methodName [, numParams]])
SKIP_METHODS = [('DrudeForceImpl',),
                ('CalcDrudeForceKernel',),
                ('IntegrateDrudeLangevinStepKernel',),
                ('IntegrateDrudeSCFStepKernel',),
]

# The build script assumes method args that are non-const references are
# used to output values. This list gives exceptions to this rule.
NO_OUTPUT_ARGS = []

# SWIG assumes the target language shadow class owns the C++ class
# so by default, when the  shadow class is deleted, the C++ class is also.
# However, if a class is passed to another class, it may be appropriate to
# change this.  The following dict lists the (Class,Methods) for which the
# shadow class should *lose* ownership of the C++ class.
# The list is the argument position(s).
STEAL_OWNERSHIP = {}

# This is a list of units to attach to return values and method args.
# Indexed by (ClassName, MethodsName)
UNITS = {
    ("DrudeLangevinIntegrator", "getDrudeTemperature") : ("unit.kelvin", ()),
    ("DrudeLangevinIntegrator", "getDrudeFriction") : ("1/unit.picosecond", ()),
    ("DrudeSCFIntegrator", "getMinimizationErrorTolerance") : ("unit.kilojoules_per_mole/unit.nanometer", ()),
}

