#!/usr/bin/env python3
"""
Compute IR spectrum from RPMD centroid dipole trajectory
=========================================================

This script calculates the IR spectrum from the centroid dipole moment 
autocorrelation function generated by RPMD simulations.

Usage:
    python compute_ir_spectrum_rpmd.py cavity_diamer_lambda0.0700.npz
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
import sys
from pathlib import Path

def compute_ir_spectrum(npz_file, cutoff_ps=20.0, max_freq_cm=3500, output_prefix=None):
    """
    Compute IR spectrum from centroid dipole trajectory.
    
    Parameters
    ----------
    npz_file : str
        Path to NPZ file with dipole trajectory
    cutoff_ps : float
        Time to skip at the beginning (ps)
    max_freq_cm : float
        Maximum frequency to plot (cm⁻¹)
    output_prefix : str, optional
        Prefix for output files
    """
    print("=" * 60)
    print("IR Spectrum Calculation from RPMD Centroid Dipoles")
    print("=" * 60)
    
    # Load data
    print(f"\nLoading data from: {npz_file}")
    data = np.load(npz_file, allow_pickle=True)
    time_ps = data['time_ps']
    dipole_nm = data['dipole_nm']
    metadata = data['metadata'].item()
    
    print(f"  Data points: {len(time_ps)}")
    print(f"  Time range: {time_ps[0]:.2f} - {time_ps[-1]:.2f} ps")
    print(f"  RPMD beads: {metadata.get('num_beads', 'unknown')}")
    print(f"  Thermostat: {metadata.get('thermostat', 'unknown')}")
    print(f"  Centroid friction: {metadata.get('centroid_friction', 'unknown')} ps^-1")
    print(f"  Lambda: {metadata.get('lambda_coupling', 'unknown')}")
    
    # Apply time cutoff
    print(f"\nApplying time cutoff: t >= {cutoff_ps} ps")
    idx_start = np.where(time_ps >= cutoff_ps)[0]
    if len(idx_start) == 0:
        print(f"  WARNING: No data after {cutoff_ps} ps!")
        idx_start = 0
    else:
        idx_start = idx_start[0]
    
    time_cut = time_ps[idx_start:]
    dipole_cut = dipole_nm[idx_start:]
    
    print(f"  Using {len(time_cut)} data points ({time_cut[0]:.2f} - {time_cut[-1]:.2f} ps)")
    
    # Calculate timestep
    dt_ps = time_cut[1] - time_cut[0] if len(time_cut) > 1 else metadata.get('dt_ps', 0.001)
    print(f"  Timestep: {dt_ps} ps ({dt_ps*1000:.2f} fs)")
    
    # Compute autocorrelation function
    print("\nComputing dipole autocorrelation function...")
    n_points = len(dipole_cut)
    autocorr = np.zeros(n_points)
    
    for i in range(3):  # x, y, z components
        d = dipole_cut[:, i]
        d = d - d.mean()  # Remove DC offset
        
        # FFT-based autocorrelation
        fft_d = np.fft.fft(d, n=2*n_points)
        power = np.abs(fft_d)**2
        autocorr_component = np.fft.ifft(power)[:n_points].real
        autocorr += autocorr_component
    
    # Normalize
    autocorr /= autocorr[0]
    print(f"  Autocorrelation computed for {n_points} points")
    
    # Apply window function to reduce spectral leakage
    print("\nApplying Blackman window...")
    window = signal.windows.blackman(len(autocorr))
    autocorr_windowed = autocorr * window
    
    # Fourier transform to get spectrum
    print("Computing IR spectrum via FFT...")
    spectrum = np.fft.rfft(autocorr_windowed)
    freqs_ps = np.fft.rfftfreq(len(autocorr), d=dt_ps)
    
    # Convert frequency from 1/ps to cm⁻¹
    # ν (cm⁻¹) = ν (THz) × 33.356 = ν (ps⁻¹) × 33.356
    c_cm_per_ps = 33.356  # Speed of light in cm/ps
    freqs_cm = freqs_ps * c_cm_per_ps
    
    # IR intensity proportional to |FT[C(t)]|²
    intensity = np.abs(spectrum)**2
    
    # Normalize intensity
    intensity = intensity / intensity.max()
    
    print(f"  Frequency range: 0 - {freqs_cm[-1]:.1f} cm⁻¹")
    print(f"  Frequency resolution: {freqs_cm[1] - freqs_cm[0]:.2f} cm⁻¹")
    
    # Determine output file prefix
    if output_prefix is None:
        base_name = Path(npz_file).stem
        output_prefix = f"cavity_ir_spectrum_{base_name.replace('cavity_diamer_', '')}"
    
    # Save spectrum data
    data_file = f"{output_prefix}_data.npz"
    np.savez(data_file,
             freqs_cm=freqs_cm,
             intensity=intensity,
             autocorr=autocorr,
             autocorr_windowed=autocorr_windowed,
             metadata=metadata)
    print(f"\nSaved spectrum data to: {data_file}")
    
    # Plot full spectrum
    plt.figure(figsize=(12, 6))
    plt.plot(freqs_cm, intensity, linewidth=0.8, color='blue', alpha=0.8)
    plt.xlim(0, max_freq_cm)
    plt.ylim(0, 1.1)
    plt.xlabel('Frequency (cm$^{-1}$)', fontsize=12)
    plt.ylabel('Normalized IR Intensity', fontsize=12)
    
    title = f"RPMD IR Spectrum ({metadata.get('num_beads', '?')} beads)"
    title += f"\n250 dimers, T={metadata.get('temperature_K', '?')} K, λ={metadata.get('lambda_coupling', '?'):.4f}"
    plt.title(title, fontsize=13)
    plt.grid(True, alpha=0.3)
    
    full_plot = f"{output_prefix}_full.png"
    plt.savefig(full_plot, dpi=300, bbox_inches='tight')
    print(f"Saved full spectrum plot to: {full_plot}")
    
    # Plot high-resolution zoom around expected peaks
    plt.figure(figsize=(14, 5))
    
    # O-O stretch region (1400-1700 cm⁻¹)
    plt.subplot(1, 2, 1)
    mask_OO = (freqs_cm >= 1400) & (freqs_cm <= 1700)
    plt.plot(freqs_cm[mask_OO], intensity[mask_OO], linewidth=1.2, color='red')
    plt.xlabel('Frequency (cm$^{-1}$)', fontsize=11)
    plt.ylabel('Normalized IR Intensity', fontsize=11)
    plt.title('O-O Stretch Region', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.axvline(1560, color='gray', linestyle='--', alpha=0.5, label='Expected 1560 cm$^{-1}$')
    plt.legend()
    
    # N-N stretch region (2200-2450 cm⁻¹)
    plt.subplot(1, 2, 2)
    mask_NN = (freqs_cm >= 2200) & (freqs_cm <= 2450)
    plt.plot(freqs_cm[mask_NN], intensity[mask_NN], linewidth=1.2, color='green')
    plt.xlabel('Frequency (cm$^{-1}$)', fontsize=11)
    plt.ylabel('Normalized IR Intensity', fontsize=11)
    plt.title('N-N Stretch Region', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.axvline(2325, color='gray', linestyle='--', alpha=0.5, label='Expected 2325 cm$^{-1}$')
    plt.legend()
    
    plt.tight_layout()
    hires_plot = f"{output_prefix}_hires.png"
    plt.savefig(hires_plot, dpi=300, bbox_inches='tight')
    print(f"Saved high-res zoom plot to: {hires_plot}")
    
    # Print peak analysis
    print("\n" + "=" * 60)
    print("Peak Analysis")
    print("=" * 60)
    
    # Find peaks in O-O region
    peaks_OO, properties_OO = signal.find_peaks(intensity[mask_OO], height=0.1)
    if len(peaks_OO) > 0:
        print("\nO-O Stretch Region (1400-1700 cm⁻¹):")
        for peak_idx in peaks_OO[:5]:  # Top 5 peaks
            freq = freqs_cm[mask_OO][peak_idx]
            height = intensity[mask_OO][peak_idx]
            print(f"  Peak at {freq:.1f} cm⁻¹ (intensity: {height:.3f})")
    else:
        print("\nO-O Stretch Region: No significant peaks found")
    
    # Find peaks in N-N region
    peaks_NN, properties_NN = signal.find_peaks(intensity[mask_NN], height=0.1)
    if len(peaks_NN) > 0:
        print("\nN-N Stretch Region (2200-2450 cm⁻¹):")
        for peak_idx in peaks_NN[:5]:  # Top 5 peaks
            freq = freqs_cm[mask_NN][peak_idx]
            height = intensity[mask_NN][peak_idx]
            print(f"  Peak at {freq:.1f} cm⁻¹ (intensity: {height:.3f})")
    else:
        print("\nN-N Stretch Region: No significant peaks found")
    
    print("\n" + "=" * 60)
    print("IR spectrum calculation complete!")
    print("=" * 60)
    
    return freqs_cm, intensity


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description='Compute IR spectrum from RPMD dipole trajectory')
    parser.add_argument('input_file', type=str,
                       help='Input NPZ file with dipole trajectory')
    parser.add_argument('--cutoff', type=float, default=20.0,
                       help='Time cutoff in ps (default: 20.0)')
    parser.add_argument('--max-freq', type=float, default=3500,
                       help='Maximum frequency in cm⁻¹ (default: 3500)')
    parser.add_argument('--output', type=str, default=None,
                       help='Output file prefix (default: auto-generated)')
    
    args = parser.parse_args()
    
    try:
        compute_ir_spectrum(args.input_file, args.cutoff, args.max_freq, args.output)
    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
