FIND_PACKAGE(Python3 REQUIRED COMPONENTS Interpreter)

FUNCTION(ADD_FORCE_IMPL_CHECK NAME HEADER_DIR LIBRARY)
    FILE(GLOB_RECURSE HEADERS CONFIGURE_DEPENDS "${HEADER_DIR}/*.h")

    SET(GENERATOR "${OPENMM_DIR}/tests/generateForceImplChecks.py")
    SET(SOURCE "${CMAKE_CURRENT_BINARY_DIR}/${NAME}.cpp")
    SET_PROPERTY(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
                 "${GENERATOR}" ${HEADERS})

    EXECUTE_PROCESS(
        COMMAND "${Python3_EXECUTABLE}" "${GENERATOR}"
                "${SOURCE}" "${HEADER_DIR}" "${OPENMM_DIR}/openmmapi/include"
        RESULT_VARIABLE RESULT
    )
    IF(NOT RESULT EQUAL 0)
        MESSAGE(FATAL_ERROR "Could not generate ${NAME}")
    ENDIF()

    ADD_EXECUTABLE(${NAME} "${SOURCE}")
    TARGET_LINK_LIBRARIES(${NAME} ${LIBRARY})
    ADD_TEST(NAME ${NAME} COMMAND ${NAME})
ENDFUNCTION()
