package:
  name: openmm
  version: !!str dev

source:
  url: https://github.com/SimTk/openmm/archive/6.0.tar.gz
  fn: 6.0.tar.gz
  patches:
    - plugin-dir.patch

build:
  number: 3

requirements:
  build:
    - cmake
    - python
    - fftw3f

  run:
    - python
    - fftw3f

about:
  home: https://simtk.org/home/openmm
  license: GPL
