rm -fr  alchemy	alchemy
rm -fr  analyze	analyze
rm -fr  anneal	anneal
rm -fr  archive	archive
rm -fr  bar	bar
rm -fr  correlate	correlate
rm -fr  crystal	crystal
rm -fr  diffuse	diffuse
rm -fr  distgeom	distgeom
rm -fr  document	document
rm -fr  dynamic	dynamic
rm -fr  gda	gda
rm -fr  intedit	intedit
rm -fr  intxyz	intxyz
rm -fr  minimize	minimize
rm -fr  minirot	minirot
rm -fr  minrigid	minrigid
rm -fr  molxyz	molxyz
rm -fr  monte	monte
rm -fr  newton	newton
rm -fr  newtrot	newtrot
rm -fr  nucleic	nucleic
rm -fr  optimize	optimize
rm -fr  optirot	optirot
rm -fr  optrigid	optrigid
rm -fr  path	path
rm -fr  pdbxyz	pdbxyz
rm -fr  polarize	polarize
rm -fr  poledit	poledit
rm -fr  potential	potential
rm -fr  prmedit	prmedit
rm -fr  protein	protein
rm -fr  pssrigid	pssrigid
rm -fr  pssrot	pssrot
rm -fr  pss	pss
rm -fr  radial	radial
rm -fr  saddle	saddle
rm -fr  scan	scan
rm -fr  sniffer	sniffer
rm -fr  spacefill	spacefill
rm -fr  spectrum	spectrum
rm -fr  superpose	superpose
rm -fr  sybylxyz	sybylxyz
rm -fr  testgrad	testgrad
rm -fr  testhess	testhess
rm -fr  testpair	testpair
rm -fr  testpol	testpol
rm -fr  testrot	testrot
rm -fr  timerot	timerot
rm -fr  timer	timer
rm -fr  torsfit	torsfit
rm -fr  valence	valence
rm -fr  vibbig	vibbig
rm -fr  vibrate	vibrate
rm -fr  vibrot	vibrot
rm -fr  xtalfit	xtalfit
rm -fr  xtalmin	xtalmin
rm -fr  xyzedit	xyzedit
rm -fr  xyzint	xyzint
rm -fr  xyzpdb	xyzpdb
rm -fr  xyzsybyl	xyzsybyl
