void  kupdate_sd1 (
		const float  xstrwidth,
		const float  gstrwidth,
		const float  goffset,
		const float  cem,
		const float  pc1,
		const float  pc2,
		const float  pc3,
		::brook::stream sdpc,
		::brook::stream fgauss,
		::brook::stream sd2X,
		::brook::stream posq,
		::brook::stream f,
		::brook::stream v,
		::brook::stream invmass,
		::brook::stream sd1V,
		::brook::stream vnew,
		::brook::stream posqp); 

void  kupdate_sd2 (
		const float  xstrwidth,
		const float  gstrwidth,
		const float  goffset,
		const float  pc1,
		const float  pc2,
		::brook::stream sdpc,
		::brook::stream fgauss,
		::brook::stream sd1V,
		::brook::stream posq,
		::brook::stream posqp,
		::brook::stream vnew,
		::brook::stream sd2X,
		::brook::stream v,
		::brook::stream posqp2); 

void  kpermute_vectors (const float  gstrwidth,
		::brook::stream perm,
		::brook::stream gvin,
		::brook::stream gvout); 

void  kupdate_sd2_fix1 (const float  xstrwidth,
		const float  gstrwidth,
		const float  goffset,
		const float  pc1,
		const float  pc2,
		::brook::stream sdpc,
		::brook::stream fgauss,
		::brook::stream sd1V,
		::brook::stream posq,
		::brook::stream posqp,
		::brook::stream vnew,
		::brook::stream sd2X,
		::brook::stream v,
		::brook::stream posqp2); 

void  kupdate_sd1_fix1 (const float  xstrwidth,
		const float  gstrwidth,
		const float  goffset,
		const float  cem,
		const float  pc1,
		const float  pc2,
		const float  pc3,
		::brook::stream sdpc,
		::brook::stream fgauss,
		::brook::stream sd2X,
		::brook::stream posq,
		::brook::stream f,
		::brook::stream v,
		::brook::stream invmass,
		::brook::stream sd1V,
		::brook::stream vnew,
		::brook::stream posqp);

void  kupdate_sd2_fix1_FixedRV(const float  xstrwidth,
		const float  gstrwidth,
		const float  goffset,
		const float  pc1,
		const float  pc2,
		::brook::stream sdpc,
		::brook::stream fgauss,
		::brook::stream sd1V,
		::brook::stream posq,
		::brook::stream posqp,
		::brook::stream vnew,
		::brook::stream sd2X,
		::brook::stream v,
		::brook::stream posqp2); 

void  kupdate_sd1_fix1_FixedRV(const float  xstrwidth,
		const float  gstrwidth,
		const float  goffset,
		const float  cem,
		const float  pc1,
		const float  pc2,
		const float  pc3,
		::brook::stream sdpc,
		::brook::stream fgauss,
		::brook::stream sd2X,
		::brook::stream posq,
		::brook::stream f,
		::brook::stream v,
		::brook::stream invmass,
		::brook::stream sd1V,
		::brook::stream vnew,
		::brook::stream posqp);
