package:
  name: openmm
  version: !!str dev

requirements:
  build:
    - cmake
    - python
    - fftw3f
    - swig

  run:
    - python
    - fftw3f
    - numpy

about:
  home: https://simtk.org/home/openmm
  license: GPL
