# VMD Movie Generation Script
# Generated by generate_movie.py
#
# Usage: vmd -e /media/extradrive/Trajectories/openmm/tests/protein_system/protein_movie.tcl

# Load topology
mol new trajectory/topology.pdb type pdb waitfor all

# Load trajectory frames
mol addfile trajectory/frame_000001_t0.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000002_t1.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000003_t1.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000004_t2.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000005_t2.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000006_t3.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000007_t3.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000008_t4.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000009_t4.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000010_t5.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000011_t5.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000012_t6.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000013_t6.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000014_t7.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000015_t7.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000016_t8.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000017_t8.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000018_t9.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000019_t9.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000020_t10.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000021_t10.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000022_t11.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000023_t11.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000024_t12.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000025_t12.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000026_t13.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000027_t13.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000028_t14.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000029_t14.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000030_t15.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000031_t15.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000032_t16.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000033_t16.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000034_t17.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000035_t17.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000036_t18.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000037_t18.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000038_t19.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000039_t19.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000040_t20.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000041_t20.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000042_t21.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000043_t21.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000044_t22.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000045_t22.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000046_t23.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000047_t23.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000048_t24.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000049_t24.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000050_t25.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000051_t25.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000052_t26.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000053_t26.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000054_t27.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000055_t27.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000056_t28.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000057_t28.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000058_t29.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000059_t29.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000060_t30.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000061_t30.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000062_t31.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000063_t31.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000064_t32.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000065_t32.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000066_t33.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000067_t33.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000068_t34.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000069_t34.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000070_t35.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000071_t35.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000072_t36.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000073_t36.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000074_t37.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000075_t37.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000076_t38.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000077_t38.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000078_t39.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000079_t39.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000080_t40.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000081_t40.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000082_t41.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000083_t41.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000084_t42.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000085_t42.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000086_t43.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000087_t43.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000088_t44.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000089_t44.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000090_t45.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000091_t45.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000092_t46.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000093_t46.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000094_t47.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000095_t47.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000096_t48.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000097_t48.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000098_t49.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000099_t49.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000100_t50.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000101_t50.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000102_t51.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000103_t51.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000104_t52.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000105_t52.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000106_t53.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000107_t53.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000108_t54.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000109_t54.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000110_t55.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000111_t55.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000112_t56.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000113_t56.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000114_t57.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000115_t57.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000116_t58.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000117_t58.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000118_t59.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000119_t59.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000120_t60.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000121_t60.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000122_t61.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000123_t61.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000124_t62.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000125_t62.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000126_t63.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000127_t63.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000128_t64.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000129_t64.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000130_t65.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000131_t65.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000132_t66.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000133_t66.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000134_t67.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000135_t67.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000136_t68.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000137_t68.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000138_t69.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000139_t69.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000140_t70.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000141_t70.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000142_t71.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000143_t71.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000144_t72.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000145_t72.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000146_t73.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000147_t73.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000148_t74.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000149_t74.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000150_t75.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000151_t75.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000152_t76.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000153_t76.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000154_t77.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000155_t77.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000156_t78.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000157_t78.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000158_t79.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000159_t79.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000160_t80.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000161_t80.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000162_t81.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000163_t81.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000164_t82.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000165_t82.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000166_t83.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000167_t83.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000168_t84.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000169_t84.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000170_t85.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000171_t85.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000172_t86.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000173_t86.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000174_t87.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000175_t87.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000176_t88.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000177_t88.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000178_t89.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000179_t89.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000180_t90.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000181_t90.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000182_t91.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000183_t91.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000184_t92.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000185_t92.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000186_t93.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000187_t93.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000188_t94.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000189_t94.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000190_t95.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000191_t95.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000192_t96.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000193_t96.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000194_t97.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000195_t97.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000196_t98.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000197_t98.5ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000198_t99.0ps.pdb type pdb waitfor all
mol addfile trajectory/frame_000199_t99.5ps.pdb type pdb waitfor all

# Set up representations
mol delrep 0 top

# Protein surface
mol representation NewCartoon
mol color Structure
mol selection {protein}
mol material Opaque
mol addrep top

# Protein surface overlay
mol representation Surf 1.4 0.0 0.0
mol color Structure  
mol selection {protein}
mol material Transparent
mol addrep top

# First solvation shell waters
mol representation VDW 0.3 12.0
mol color ColorID 23
mol selection {water and within 5.0 of protein}
mol material Transparent
mol addrep top

# Set up display
display projection Orthographic
display depthcue off
axes location Off
color Display Background white
display resize 1920 1080

# Center on protein
mol top 0
display resetview

# Render movie frames
set nframes [molinfo top get numframes]
set framedir "/media/extradrive/Trajectories/openmm/tests/protein_system/vmd_frames"
file mkdir $framedir

for {set i 0} {$i < $nframes} {incr i} {
    animate goto $i
    display update
    
    # Optional rotation
    rotate y by 1.0
    
    # Render
    set filename [format "$framedir/frame_%06d.tga" $i]
    render TachyonInternal $filename
    
    puts "Rendered frame $i / $nframes"
}

puts "Done! Compile with: ffmpeg -framerate 24 -i vmd_frames/frame_%06d.tga -c:v libx264 -pix_fmt yuv420p movie.mp4"
quit
